export const POLL_PARTICIPATION_REWARD_POINTS = 10;
export const POLL_CREATE_REWARD_POINTS = 20;
export const POLL_POPULAR_BONUS_POINTS = 30;

export const POLL_MAX_REWARD_POINTS =
  POLL_CREATE_REWARD_POINTS + POLL_POPULAR_BONUS_POINTS;
